### ISSUE TITLE
Version file does not support line ending (.node-version)

### ISSUE THREAD

**Issue by shadowspawn** [BeeeQueue/nvm-rust#198]
Text files often have a line-ending. Depending on the editor, it may be difficult for the user to tell if there is a line-ending or not, or possibly the editor may add one automatically.

It looks like from my limited testing that nvm-rust does not allow the version file to have a trailing line-ending:

```
% hexdump -C .node-version 
00000000  31 30 2e 31 32 2e 30 0a                           |10.12.0.|
00000008
% nvm install       
Failed to parse .node-version: '10.12.0
'
Error: You did not pass a version and we did not find any version files (package.json#engines, .nvmrc) in the current directory.
```

(Full disclosure. I am not a user of `nvm-rust`! I took a look because I am interested in application support for `.node-version`: https://github.com/shadowspawn/node-version-usage)

**Comment by BeeeQueue** [comment]
Thank you for the report!
